df <- read.table('household_power_consumption.txt',sep=';',header=TRUE,na.strings='?')
cleandf <- df[which(df$Date=='1/2/2007'|df$Date=='2/2/2007'),] 
rm(df)
library(lubridate)
cleandf$Datetime <- with(cleandf, dmy(Date) + hms(Time))
png(filename='plot3.png',width=480,height=480)
plot(cleandf$Datetime,cleandf$Sub_metering_1,xlab='',ylab='Energy sub metering',type='l')
lines(cleandf$Datetime,cleandf$Sub_metering_2,col='red',type='l')
lines(cleandf$Datetime,cleandf$Sub_metering_3,col='blue',type='l')
legend('topright',lty=1,col=c('black','red','blue'),legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
dev.off()
